trigger:
  - main

variables:
  imageName: 'myapp'                     # replace or parameterize
  imageTag: '$(Build.BuildId)'
  azureContainerRegistry: '<acrLoginServer>'    # e.g. myregistry.azurecr.io

stages:
- stage: BuildAndPush
  displayName: Build and push Docker image
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build and push
      inputs:
        command: buildAndPush
        containerRegistry: '<acrServiceConnection>'   # Service connection name for ACR (Azure RM)
        repository: '$(imageName)'
        dockerfile: '**/Dockerfile'
        tags: |
          $(imageTag)

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: imageInfo

- stage: Deploy
  displayName: Deploy container to App Service
  dependsOn: BuildAndPush
  jobs:
  - deployment: DeployContainer
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: '<azureServiceConnection>'
              appType: 'webAppLinux'
              appName: '<appServiceNameContainer>'
              images: |
                $(azureContainerRegistry)/$(imageName):$(imageTag)
